### PR TITLE
finished landing page styling

### PR DESCRIPTION
**Pull request by anquail**
### Summary of Changes

- The changes in this PR add default values to the material ui theme, perform a basic CSS reset, and add styling to the landing page.
---

### Summary of Implementation Logic

- Replaces copy on existing landing page to match Figma prototype
- Performs css reset using CssBaseLine component from Material ui (normalizes padding, margins, box-sizing, etc.) 
- Adds inter as a font to material ui theme
- Adds default background and primary text colors to material ui theme 
- Alters material ui theme to remove text decoration from all anchor tags by default
- Adds module augmentation for material ui DefaultTheme (Typescript fix necessary in MUI v5)
- Adds styling to landing page to match Figma prototype
---

### Issue Link

Original Issue: https://github.com/users/RubySpeeders/projects/1/views/1?pane=issue&itemId=37304424

Dependent Issues:

Depends on Issues:

---

### Screen shots / Videos

Screenshot 2023-09-09 at 10 23 44 PM

---

### Acceptance Criteria

- [x] When landing page is loaded, the design should match the Figma prototype
---

### Checklist for PR Owner

- [x] Standardized PR Title
- [x] Included relevant videos and screen shots
- [x] Included Summary of Changes
- [x] Included Summary of Implementation Logic
- [x] Acceptance Criteria are fufilled

### CODE REVIEW

**Review by charlottekies — APPROVED** [review]
nice!

**Review by RubySpeeders — APPROVED** [review]
looks amazing!

**Comment by cheesehero112** [comment]
@anquail nice work!! Do you want to go ahead and merge this to the develop branch, then PR to the main branch to trigger deployment?

**Comment by anquail** [comment]
@cheesehero112 okay I think I just did what you suggested! Let me know if that's what you had in mind

**Pull request merged**
